### ISSUE TITLE
sourcing D1

### ISSUE THREAD

**Issue by hajdbo** [CedarGroveStudios/Classic_MIDI_FeatherWing#1]
D1 1N4001 is a through-hole ref, and the smallest close match I found (general purpose 50V 1A) is a SOD123F, which does not fit the footprint.

Can you point to a ref #?

**Comment by CedarGroveStudios** [comment]
Sorry about that. I've been using an SD0805S040S0R5 (40v 0.5A Schottky), DigiKey #478-7802-1-ND
[https://www.digikey.com/products/en?keywords=478-7802-1-ND](url)

**Comment by hajdbo** [comment]
thank you!
